id = 9
title = 'Multi-proyecto / Monorepo jerárquico'
description = 'Proyecto → apps → tareas, CLI unificado que navega todo'
state = 'todo'
created = '2026-08-17T14:21:53-03:00'
updated = '2026-08-17T14:21:53-03:00'
