id = 10
title = 'Blame de git por tarea'
description = 'Asignar autor a item y vincular líneas de código específicas'
state = 'todo'
created = '2026-08-17T14:21:53-03:00'
updated = '2026-08-17T14:21:53-03:00'
