id = 11
title = 'Documentación centralizada en .pm/docs/'
description = 'Carpeta .pm/docs/ para archivos markdown referenciados por items'
state = 'todo'
created = '2026-08-17T14:21:53-03:00'
updated = '2026-08-17T14:21:53-03:00'
