id = 16
title = 'Implementar pj edit'
description = 'Abrir item en $EDITOR para modificar título, descripción y estado manualmente'
state = 'todo'
created = '2026-08-17T14:24:13-03:00'
updated = '2026-08-17T14:24:13-03:00'
